Repository CA-G12/Saeed-Mai-Movie, pull requests merged in 2022-08, with the labels that each got.

#4 create File structure
  index.html
  js/dom/anime.js
  js/dom/fetch.js
  js/dom/movies.js
  js/dom/wish.js
  js/localStorage.js
  js/logic.js
  js/test.js
  media/genStyle/style.css
  pages/anime.html
  pages/movie.html
  pages/wish.html
  style/home.css
  style/movie.css
Labels: awaiting preview

#6 write html and css for movies page
  index.html
  pages/movie.html
  style/movie.css
Labels: awaiting preview

#12 create css file to wish page and write html
  pages/movie.html
  pages/wish.html
  style/movie.css
  style/wish.css
Labels: awaiting preview

#11 Fetch Function
  js/dom/fetch.js
Labels: awaiting preview

#13 search function
  .gitignore
  js/logic.js
  js/test.js
  package.json
Labels: Done

#14 write local storage helpers functions
  js/localStorage.js
  js/localStorage.test.js
  js/test.js
Labels: Done

#21 fetch anime movies
  js/dom/anime.js
  pages/anime.html
Labels: Done

#23 fetch data Show Movies
  js/dom/movies.js
  js/logic.js
  js/test.js
  pages/movie.html
Labels: awaiting preview, Done

#24 make search functionality in dom anime page and make some fixes in al…
  index.html
  js/dom/anime.js
  js/dom/wish.js
  js/localStorage.js
  media/genStyle/style.css
  pages/anime.html
  pages/wish.html
  style/movie.css
Labels: awaiting preview

#28 simple edit
  pages/movie.html
Labels: Done

#29 write read me File
  README.md
Labels: Done

#31 Simple edits
  index.html
  style/home.css
Labels: Done

#33 Edit head width in pages
  js/dom/movies.js
  style/movie.css
Labels: Done

#35 Edit not found div css and text content
  js/dom/anime.js
  js/dom/movies.js
Labels: Done

#36 write local storage functionality
  README.md
  js/dom/anime.js
  js/dom/wish.js
  js/localStorage.js
  style/movie.css
Labels: To Do
